### ISSUE TITLE
Is there a way to overflow text widgets inside contentBuilder?

### ISSUE THREAD

**Issue by samuel-s-marques** [netglade/sliver_app_bar_builder#3]
I'm currently using this package in my app and I'm wondering if there's a way to overflow a text widget inside the contentBuilder. Here are the screenshots of [storybook demo](https://netglade.github.io/sliver_app_bar_builder/#/) using iPhone 12 Mini layout, for example:

1. A long appbar text title:
![image](https://user-images.githubusercontent.com/73559465/226154010-407bb335-2bb8-4dd2-9f04-e7d1c735bb26.png)

2. The Text widget when shrunken:
![image](https://user-images.githubusercontent.com/73559465/226154075-927f5521-3599-40eb-9fa2-357cb614f656.png)

It would be great to add an ellipsis at the end.

**Comment by tenhobi** [comment]
Hi @samuel-s-marques, yea, it's possible. We are doing that in our app -- multi-line on start, one line with an ellipsis when shrunken. I will tell you how ASAP when I am on my computer.

I should probably add some storybooks to show examples like this.

**Comment by samuel-s-marques** [comment]
@tenhobi, thank you. I appreciate your prompt response and willingness to assist.

**Comment by tenhobi** [comment]
@samuel-s-marques fixed the default story so the text is wrapped correctly. Previously I used `Matrix4` which "moves" already rendered widget and so the text didn't wrap correctly as seen on your screenshot.
 
<img width="133" alt="image" src="https://user-images.githubusercontent.com/5287596/226253929-410e0ba9-86ee-435f-8eb7-5b2d96955be7.png">

For the second story "Multiline to one line" I implemented an example of how to handle the case when you start to shrink the app bar to switch to one line. You can modify the threshold and play with it. 👍 

The example uses TextPainter, so I can work with text height etc. If somebody has a better idea, please fill out a PR. :)

**Comment by samuel-s-marques** [comment]
I just tested and it looks great! Thank you!
